services:
  db:
    image: "pgvector/pgvector:pg16"
    ports:
      - "5433:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_USER=user
      - POSTGRES_DB=explore
